---
bot_settings:
  debug_mode: true
  default_status: ""
  embed_footer: "Enjoy life, while it lasts... And remember, Don't Starve!"
  prefix: "b|"
intents:
  bans: true
  emojis: true
  guilds: true
  members: true
  message_content: true
  messages: true
  reactions: true
  voice_states: true
